#!/bin/bash

if [ $# -ne 3 ]; then
  echo "USAGE: ${PROG:-$0} REQUEST_TYPE NAME OUTPUT_DIR"
  exit 1
fi

fail() {
  echo "ERROR: $1"
  exit 1
}

set -e
test "$1" = "client" || test "$1" = "server" || \
  fail "REQUEST_TYPE must be client or server"
test -d "$3" || fail "OUTPUT_DIR must be a valid directory"

pushd /certs/server > /dev/null
echo | ./easyrsa gen-req "$2" nopass
cd /certs/ca
./easyrsa import-req "/certs/server/pki/reqs/$2.req" "$2"
echo "yes" | ./easyrsa sign-req "$1" "$2"
popd > /dev/null
cp "/certs/ca/pki/issued/$2.crt" "$3"
cp "/certs/server/pki/private/$2.key" "$3"
