#!/bin/bash

CONF_DIR=/etc/openvpn/server/
DEF_IPNET=10.8.0.0/24
IPNET=10.8.0.0

set -e

mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

if [ $# -ge 1 ]; then
  IPNET=$1
fi

sed -i $CONF_DIR/server.conf \
  -e '/^server / {' \
  -e   "iserver $IPNET 255.255.255.0" \
  -e   "d" \
  -e '}'
sed -i /etc/ufw/before.rules -e "s,$DEF_IPNET,$IPNET/24,"

ufw enable

rm -rf /certs

openvpn --cd $CONF_DIR --config $CONF_DIR/server.conf

