#!/bin/bash

set -e

PROG="${PROG:-$0}"
CACERTD=/mnt/certs/ca
SERVERD=/mnt/certs/server

fail() {
  echo "ERROR: $PROG: $1" >&2
  exit 1
}

if [ $# -ne 3 ]; then
  echo "USAGE: ${PROG} REQUEST_TYPE NAME OUTPUT_DIR" >&2
  exit 1
fi

if [ ! -f "$CACERTD/pki/ca.crt" ]; then
  fail "Need to run \`ovpn init ca\` before this"
fi

if [ ! -d "$SERVERD/pki" ]; then
  fail "Need to run \`ovpn init server\` before this"
fi

test "$1" = "client" || test "$1" = "server" || \
  fail "REQUEST_TYPE must be client or server"
test -d "$3" || fail "OUTPUT_DIR must be a valid directory"

pushd $SERVERD > /dev/null
echo | ./easyrsa gen-req "$2" nopass
cd $CACERTD
./easyrsa import-req "$SERVERD/pki/reqs/$2.req" "$2"
echo "yes" | ./easyrsa sign-req "$1" "$2"
popd > /dev/null
cp "$CACERTD/pki/issued/$2.crt" "$3"
cp "$SERVERD/pki/private/$2.key" "$3"
